xedisk - Atari XL/XE Disk Image Utility
=======================================

// This file is in AsciiDoc format. It is the source for README.html.
:Compact-Option:

+xedisk+ is a small command-line utility for manipulating Atari disk image files.
It supports basic operations on raw sectors as well as on files contained on disks.

+xedisk+ is written in http://www.digitalmars.com/d/2.0/[D programming language] and tested
under Windows and Linux (x86). However, it should be possible to build and run it on any
platform, for which D compiler is available.
It is designed to be easily embeddable in build scripts.

Supported disk image formats
----------------------------

Currently only ATR format is supported.

Supported filesystems
---------------------

Currently only MyDos filesystem is supported.

Installation
------------

You need http://www.digitalmars.com/d/download.html[DMD 2.047], and a GNU compatible make to build +xedisk+.

Go to console window, and, depending on your operating system, type

--------------
> mingw32-make
--------------

or simply

--------------
$ make
--------------

After successful build, you can move file +xedisk.exe+ or +xedisk+ to a directory within your +PATH+.

If you like hacking, you can easily do without make, and you can use different D compiler.

Usage
-----

A general syntax is:

----------------------------
$ xedisk command [disk_image_file] [options] 
----------------------------

You can place options wherever you wish in the command line, as well as bundle
single-letter options together, if they do not require parameters.

If the command does not require writing into image, file is opened as read-only,
so you don't need write access rights to the file.

Feedback
--------

Recommended way to report issues with +xedisk+ is to use http://github.com/epi/xedisk/issues[this tracker].
You can also send bug reports, patches and feature requests to +epi at atari8 dot info+.

Authors
-------

Adrian Matoga::
"Code, idea, design".

License
-------

------------------------------------
Poetic License:

This work 'as-is' we provide.
No warranty express or implied.
We've done our best,
to debug and test.
Liability for damages denied.

Permission is granted hereby,
to copy, share, and modify.
Use as is fit,
free or for profit.
These rights, on this notice, rely.
------------------------------------
