.\" Manpage for xedisk.
.TH xedisk 1 "26 Aug 2012" "1.0" "xedisk man page"
.SH NAME
xedisk \- manipulate Atari 8-bit disk images
.SH SYNOPSIS
.sp
.nf
xedisk \fI<command>\fR [\fI<args>\fR]
xedisk [-h|--help|help] [\fI<command>\fR]
xedisk [--version]
.ni
.sp
.SH DESCRIPTION
xedisk is a command line utility for manipulating the contents of Atari 8-bit
disk images, such as the ATR files. Implemented image formats include
ATR and XFD. Currently the only implemented file system is MyDOS.
.SH OPTIONS
The full documentation and source code are available at
https://github.com/epi/xedisk/.
.SH SEE ALSO
xebin(1)
.SH REPORTING BUGS
Use the issue tracker at https://github.com/epi/xedisk/issues.
.SH AUTHOR
Written by Adrian Matoga
